apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qagwikfvq-python 
  janus-idp.io/tekton: qagwikfvq-python
  backstage.io/kubernetes-id: qagwikfvq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qagwikfvq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  