apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qagwikfvq-python
  janus-idp.io/tekton: qagwikfvq-python
  backstage.io/kubernetes-id: qagwikfvq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qagwikfvq-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
